// =============================================================================
// ReputeCare AI — Comprehensive Mock Data Library
// All realistic data for demo/development mode
// =============================================================================

export const mockOrganization = {
  id: "org_1",
  name: "HealthFirst Medical Group",
  slug: "healthfirst",
  logo: null,
  plan: "enterprise",
  createdAt: new Date("2024-01-15"),
};

export const mockLocations = [
  {
    id: "clinic_1",
    name: "Main Street Medical Center",
    address: "245 Main Street, Austin, TX 78701",
    phone: "(512) 555-0101",
    overallRating: 4.8,
    totalReviews: 1247,
    reputationScore: 96,
    reviewVelocity: "+12%",
    responseTime: "1.2h",
    googleRating: 4.9,
    healthgradesRating: 4.7,
    facebookRating: 4.8,
    yelpRating: 4.6,
    status: "excellent",
    providers: 8,
    monthlyPatients: 1840,
  },
  {
    id: "clinic_2",
    name: "Westside Family Clinic",
    address: "789 Westlake Dr, Austin, TX 78746",
    phone: "(512) 555-0202",
    overallRating: 4.5,
    totalReviews: 843,
    reputationScore: 88,
    reviewVelocity: "+7%",
    responseTime: "2.8h",
    googleRating: 4.6,
    healthgradesRating: 4.4,
    facebookRating: 4.5,
    yelpRating: 4.3,
    status: "good",
    providers: 5,
    monthlyPatients: 1120,
  },
  {
    id: "clinic_3",
    name: "Downtown Dental & Wellness",
    address: "101 Congress Ave, Austin, TX 78701",
    phone: "(512) 555-0303",
    overallRating: 4.7,
    totalReviews: 612,
    reputationScore: 92,
    reviewVelocity: "+18%",
    responseTime: "0.9h",
    googleRating: 4.8,
    healthgradesRating: 4.6,
    facebookRating: 4.7,
    yelpRating: 4.5,
    status: "excellent",
    providers: 4,
    monthlyPatients: 780,
  },
];

export const mockDashboardKPIs = {
  averageRating: 4.7,
  ratingTrend: "+0.2",
  totalReviews: 2702,
  reviewsThisMonth: 184,
  reviewVelocity: "+14%",
  reputationScore: 94,
  reputationScoreTrend: "+3",
  requestsSent: 1248,
  conversionRate: 68.4,
  conversionTrend: "+5.2%",
  negativeFeedbackRate: 3.2,
  negativeFeedbackTrend: "-1.1%",
  responseTime: "1.6h",
  responseTimeTrend: "-22%",
  referralRate: 24.7,
  referralTrend: "+8%",
  estimatedRevenueImpact: "$128,400",
  revenueImpactTrend: "+18%",
};

export const mockReviewTrendData = [
  { month: "Jan", google: 38, healthgrades: 22, facebook: 14, yelp: 8, total: 82 },
  { month: "Feb", google: 42, healthgrades: 25, facebook: 16, yelp: 10, total: 93 },
  { month: "Mar", google: 51, healthgrades: 28, facebook: 18, yelp: 11, total: 108 },
  { month: "Apr", google: 48, healthgrades: 31, facebook: 20, yelp: 9, total: 108 },
  { month: "May", google: 62, healthgrades: 34, facebook: 22, yelp: 13, total: 131 },
  { month: "Jun", google: 71, healthgrades: 38, facebook: 26, yelp: 15, total: 150 },
  { month: "Jul", google: 84, healthgrades: 42, facebook: 29, yelp: 17, total: 172 },
  { month: "Aug", google: 79, healthgrades: 45, facebook: 31, yelp: 18, total: 173 },
  { month: "Sep", google: 91, healthgrades: 49, facebook: 34, yelp: 20, total: 194 },
  { month: "Oct", google: 98, healthgrades: 52, facebook: 36, yelp: 22, total: 208 },
  { month: "Nov", google: 88, healthgrades: 55, facebook: 38, yelp: 21, total: 202 },
  { month: "Dec", google: 107, healthgrades: 58, facebook: 41, yelp: 24, total: 230 },
];

export const mockSentimentData = [
  { name: "Very Positive", value: 52, color: "#10b981" },
  { name: "Positive", value: 28, color: "#34d399" },
  { name: "Neutral", value: 12, color: "#94a3b8" },
  { name: "Negative", value: 6, color: "#f97316" },
  { name: "Very Negative", value: 2, color: "#ef4444" },
];

export const mockAIInsights = [
  {
    id: "insight_1",
    type: "opportunity",
    priority: "high",
    title: "47 patients ready for review requests",
    description: "AI has identified 47 patients from last week's appointments with 90%+ satisfaction probability. Requesting reviews now could add ~32 new 5-star reviews.",
    action: "Launch Campaign",
    impact: "+32 reviews",
    confidence: 94,
    agent: "Review Agent",
  },
  {
    id: "insight_2",
    type: "warning",
    priority: "high",
    title: "3 patients showing dissatisfaction signals",
    description: "Sentiment analysis detected frustration patterns in portal messages from 3 patients. Early intervention recommended before public reviews are posted.",
    action: "View Patients",
    impact: "Prevent 3 negative reviews",
    confidence: 87,
    agent: "Sentiment Agent",
  },
  {
    id: "insight_3",
    type: "growth",
    priority: "medium",
    title: "Westside Clinic response time dragging rating",
    description: "Westside Clinic's 2.8h average response time is 74% slower than your top location. Faster responses correlate with 0.3★ higher ratings.",
    action: "View Analytics",
    impact: "+0.3 rating",
    confidence: 91,
    agent: "SEO Agent",
  },
  {
    id: "insight_4",
    type: "referral",
    priority: "medium",
    title: "18 high-satisfaction patients — referral opportunity",
    description: "18 recent patients scored 9-10 on NPS and haven't been asked for referrals. These are your top advocates — engage now.",
    action: "Send Referral Request",
    impact: "+$24,600 potential revenue",
    confidence: 82,
    agent: "Referral Agent",
  },
  {
    id: "insight_5",
    type: "competitor",
    priority: "low",
    title: "Competitor gaining ground on Healthgrades",
    description: "Austin Family Care gained 28 reviews on Healthgrades last month vs your 18. They are closing the rating gap (now 4.5 vs your 4.7).",
    action: "View Benchmarks",
    impact: "Competitive defense",
    confidence: 89,
    agent: "SEO Agent",
  },
];

export const mockRecentActivity = [
  { id: 1, type: "review_received", patient: "Sarah M.", platform: "Google", rating: 5, time: "2 min ago", content: "Absolutely outstanding care! Dr. Chen was thorough and compassionate." },
  { id: 2, type: "request_sent", patient: "James R.", platform: "Healthgrades", rating: null, time: "18 min ago", content: "Review request sent via SMS" },
  { id: 3, type: "negative_flagged", patient: "Linda K.", platform: "Internal", rating: 2, time: "34 min ago", content: "Routed to private feedback — wait time complaint" },
  { id: 4, type: "response_posted", patient: "Michael T.", platform: "Google", rating: 4, time: "1h ago", content: "AI-drafted response approved and posted" },
  { id: 5, type: "review_received", patient: "Emma P.", platform: "Facebook", rating: 5, time: "2h ago", content: "Best dental experience I've ever had!" },
  { id: 6, type: "referral_sent", patient: "David W.", platform: "Email", rating: null, time: "3h ago", content: "Referral campaign triggered — high NPS score" },
];

export const mockPatients = [
  {
    id: "pat_1",
    name: "Sarah Mitchell",
    email: "sarah.m@email.com",
    phone: "(512) 555-1001",
    lastVisit: "2026-07-03",
    provider: "Dr. Emily Chen",
    location: "Main Street Medical Center",
    satisfactionScore: 97,
    npsScore: 10,
    sentiment: "very_positive",
    reviewStatus: "requested",
    referralLikelihood: 94,
    segment: "promoter",
    tags: ["loyal", "high-value", "advocate"],
    visitCount: 12,
  },
  {
    id: "pat_2",
    name: "James Rodriguez",
    email: "james.r@email.com",
    phone: "(512) 555-1002",
    lastVisit: "2026-07-02",
    provider: "Dr. Marcus Johnson",
    location: "Westside Family Clinic",
    satisfactionScore: 88,
    npsScore: 8,
    sentiment: "positive",
    reviewStatus: "pending",
    referralLikelihood: 71,
    segment: "promoter",
    tags: ["regular"],
    visitCount: 5,
  },
  {
    id: "pat_3",
    name: "Linda Kowalski",
    email: "linda.k@email.com",
    phone: "(512) 555-1003",
    lastVisit: "2026-07-04",
    provider: "Dr. Priya Sharma",
    location: "Main Street Medical Center",
    satisfactionScore: 42,
    npsScore: 3,
    sentiment: "negative",
    reviewStatus: "routed_private",
    referralLikelihood: 8,
    segment: "detractor",
    tags: ["at-risk", "wait-time-complaint"],
    visitCount: 2,
  },
  {
    id: "pat_4",
    name: "Michael Thompson",
    email: "m.thompson@email.com",
    phone: "(512) 555-1004",
    lastVisit: "2026-06-28",
    provider: "Dr. Emily Chen",
    location: "Main Street Medical Center",
    satisfactionScore: 91,
    npsScore: 9,
    sentiment: "very_positive",
    reviewStatus: "completed",
    referralLikelihood: 88,
    segment: "promoter",
    tags: ["advocate", "reviewer"],
    visitCount: 8,
  },
  {
    id: "pat_5",
    name: "Emma Patterson",
    email: "emma.p@email.com",
    phone: "(512) 555-1005",
    lastVisit: "2026-07-01",
    provider: "Dr. James Whitfield",
    location: "Downtown Dental & Wellness",
    satisfactionScore: 99,
    npsScore: 10,
    sentiment: "very_positive",
    reviewStatus: "completed",
    referralLikelihood: 97,
    segment: "promoter",
    tags: ["loyal", "high-value", "advocate", "referrer"],
    visitCount: 18,
  },
  {
    id: "pat_6",
    name: "David Walker",
    email: "d.walker@email.com",
    phone: "(512) 555-1006",
    lastVisit: "2026-06-30",
    provider: "Dr. Marcus Johnson",
    location: "Westside Family Clinic",
    satisfactionScore: 83,
    npsScore: 7,
    sentiment: "positive",
    reviewStatus: "pending",
    referralLikelihood: 62,
    segment: "passive",
    tags: ["regular"],
    visitCount: 3,
  },
  {
    id: "pat_7",
    name: "Rachel Green",
    email: "rachel.g@email.com",
    phone: "(512) 555-1007",
    lastVisit: "2026-07-05",
    provider: "Dr. Priya Sharma",
    location: "Main Street Medical Center",
    satisfactionScore: 58,
    npsScore: 4,
    sentiment: "negative",
    reviewStatus: "routed_private",
    referralLikelihood: 15,
    segment: "detractor",
    tags: ["at-risk", "billing-complaint"],
    visitCount: 1,
  },
  {
    id: "pat_8",
    name: "Carlos Mendez",
    email: "c.mendez@email.com",
    phone: "(512) 555-1008",
    lastVisit: "2026-07-04",
    provider: "Dr. James Whitfield",
    location: "Downtown Dental & Wellness",
    satisfactionScore: 94,
    npsScore: 9,
    sentiment: "very_positive",
    reviewStatus: "requested",
    referralLikelihood: 87,
    segment: "promoter",
    tags: ["new-patient", "advocate"],
    visitCount: 2,
  },
];

export const mockReviews = [
  {
    id: "rev_1",
    patient: "Sarah M.",
    platform: "google",
    rating: 5,
    content: "Absolutely outstanding care! Dr. Chen was thorough, compassionate, and took time to explain everything clearly. The staff was warm and welcoming. Best medical experience I've had.",
    date: "2026-07-03",
    responded: true,
    aiResponse: "Thank you so much for your kind words! We are thrilled to hear about your positive experience with our team. Your health and comfort are our top priorities.",
    sentiment: "very_positive",
    location: "Main Street Medical Center",
  },
  {
    id: "rev_2",
    patient: "Michael T.",
    platform: "google",
    rating: 4,
    content: "Great doctor and friendly staff. Waiting room was a bit busy but the care itself was excellent. Will definitely return.",
    date: "2026-06-28",
    responded: true,
    aiResponse: "Thank you for taking the time to share your experience! We appreciate your patience and are so glad you enjoyed your care.",
    sentiment: "positive",
    location: "Main Street Medical Center",
  },
  {
    id: "rev_3",
    patient: "Emma P.",
    platform: "facebook",
    rating: 5,
    content: "Best dental experience I've ever had! Dr. Whitfield is absolutely amazing. The team made me feel so comfortable. Highly recommend Downtown Dental!",
    date: "2026-07-01",
    responded: false,
    aiResponse: "We are so happy to hear you had a wonderful experience! Dr. Whitfield and the whole team love taking care of our patients. Thank you for the recommendation!",
    sentiment: "very_positive",
    location: "Downtown Dental & Wellness",
  },
  {
    id: "rev_4",
    patient: "Anonymous",
    platform: "healthgrades",
    rating: 2,
    content: "Waited 45 minutes past my appointment time with no explanation. The doctor visit itself was fine but the scheduling is a real problem.",
    date: "2026-07-04",
    responded: false,
    aiResponse: "Thank you for sharing your experience. We sincerely apologize for the wait time. We take scheduling seriously and are actively working to improve. We'd love to discuss this further — please reach out to our patient care team.",
    sentiment: "negative",
    location: "Westside Family Clinic",
  },
  {
    id: "rev_5",
    patient: "Carlos M.",
    platform: "google",
    rating: 5,
    content: "First visit and I'm already a fan! Professional, clean, friendly and efficient. Dr. Whitfield explained my treatment plan so clearly. 10/10 would recommend.",
    date: "2026-07-04",
    responded: false,
    aiResponse: "Welcome to our practice and thank you for such a kind review! We're delighted that your first visit exceeded expectations.",
    sentiment: "very_positive",
    location: "Downtown Dental & Wellness",
  },
];

export const mockCampaigns = [
  {
    id: "camp_1",
    name: "Post-Visit Feedback Request",
    type: "review_request",
    status: "active",
    trigger: "24h after appointment",
    channel: ["sms", "email"],
    sent: 1248,
    opened: 891,
    converted: 312,
    conversionRate: 25.0,
    targetSegment: "all_patients",
    locations: ["all"],
    createdAt: "2026-01-10",
  },
  {
    id: "camp_2",
    name: "Surgery Follow-Up Care",
    type: "feedback",
    status: "active",
    trigger: "72h after procedure",
    channel: ["email"],
    sent: 284,
    opened: 241,
    converted: 198,
    conversionRate: 69.7,
    targetSegment: "post_surgery",
    locations: ["clinic_1"],
    createdAt: "2026-02-14",
  },
  {
    id: "camp_3",
    name: "Annual Checkup Reminder",
    type: "referral",
    status: "active",
    trigger: "11 months after last visit",
    channel: ["sms", "email"],
    sent: 567,
    opened: 423,
    converted: 156,
    conversionRate: 27.5,
    targetSegment: "annual_patients",
    locations: ["all"],
    createdAt: "2026-03-01",
  },
  {
    id: "camp_4",
    name: "New Patient Welcome Series",
    type: "review_request",
    status: "active",
    trigger: "7 days after first visit",
    channel: ["email"],
    sent: 189,
    opened: 162,
    converted: 87,
    conversionRate: 46.0,
    targetSegment: "new_patients",
    locations: ["all"],
    createdAt: "2026-04-12",
  },
  {
    id: "camp_5",
    name: "Pediatric Visit Follow-Up",
    type: "feedback",
    status: "paused",
    trigger: "48h after appointment",
    channel: ["sms"],
    sent: 134,
    opened: 98,
    converted: 42,
    conversionRate: 31.3,
    targetSegment: "pediatric",
    locations: ["clinic_1", "clinic_2"],
    createdAt: "2026-05-08",
  },
  {
    id: "camp_6",
    name: "Dental Cleaning Thank You",
    type: "review_request",
    status: "active",
    trigger: "24h after cleaning",
    channel: ["sms", "email"],
    sent: 312,
    opened: 267,
    converted: 142,
    conversionRate: 45.5,
    targetSegment: "dental_patients",
    locations: ["clinic_3"],
    createdAt: "2026-05-20",
  },
];

export const mockFeedback = [
  {
    id: "fb_1",
    patient: "Sarah M.",
    date: "2026-07-03",
    nps: 10,
    waitTime: 5,
    staff: 5,
    doctor: 5,
    communication: 5,
    billing: 4,
    facility: 5,
    overallScore: 97,
    sentiment: "very_positive",
    comments: "Dr. Chen is absolutely wonderful. I never feel rushed.",
    location: "Main Street Medical Center",
    routed: "google_review",
  },
  {
    id: "fb_2",
    patient: "Linda K.",
    date: "2026-07-04",
    nps: 3,
    waitTime: 1,
    staff: 3,
    doctor: 4,
    communication: 2,
    billing: 3,
    facility: 4,
    overallScore: 42,
    sentiment: "negative",
    comments: "Waited over 40 minutes with no one informing me of the delay. Very frustrating.",
    location: "Main Street Medical Center",
    routed: "private_form",
  },
  {
    id: "fb_3",
    patient: "Emma P.",
    date: "2026-07-01",
    nps: 10,
    waitTime: 4,
    staff: 5,
    doctor: 5,
    communication: 5,
    billing: 5,
    facility: 5,
    overallScore: 99,
    sentiment: "very_positive",
    comments: "Perfect in every way. Dr. Whitfield is a gem.",
    location: "Downtown Dental & Wellness",
    routed: "facebook_review",
  },
  {
    id: "fb_4",
    patient: "Rachel G.",
    date: "2026-07-05",
    nps: 4,
    waitTime: 3,
    staff: 4,
    doctor: 4,
    communication: 2,
    billing: 1,
    facility: 4,
    overallScore: 58,
    sentiment: "negative",
    comments: "Billing was confusing and I was charged for something that should have been covered.",
    location: "Main Street Medical Center",
    routed: "private_form",
  },
];

export const mockFeedbackCategories = [
  { category: "Staff Friendliness", avgScore: 4.7, trend: "+0.2", responses: 892 },
  { category: "Doctor Quality", avgScore: 4.8, trend: "+0.1", responses: 892 },
  { category: "Wait Time", avgScore: 3.9, trend: "-0.3", responses: 892 },
  { category: "Communication", avgScore: 4.4, trend: "+0.4", responses: 892 },
  { category: "Billing", avgScore: 3.8, trend: "-0.1", responses: 892 },
  { category: "Facility", avgScore: 4.6, trend: "+0.2", responses: 892 },
];

export const mockReputation = {
  overallScore: 94,
  overallRating: 4.7,
  totalReviews: 2702,
  platforms: {
    google: { rating: 4.8, reviews: 1456, trend: "+0.1" },
    healthgrades: { rating: 4.6, reviews: 712, trend: "+0.2" },
    facebook: { rating: 4.7, reviews: 389, trend: "0" },
    yelp: { rating: 4.5, reviews: 145, trend: "+0.1" },
  },
  velocity: {
    daily: 6.1,
    weekly: 42,
    monthly: 184,
    trend: "+14%",
  },
  responseRate: 87,
  avgResponseTime: "1.6h",
};

export const mockReputationTimeline = [
  { month: "Jan", score: 84, rating: 4.4 },
  { month: "Feb", score: 86, rating: 4.5 },
  { month: "Mar", score: 87, rating: 4.5 },
  { month: "Apr", score: 89, rating: 4.6 },
  { month: "May", score: 90, rating: 4.6 },
  { month: "Jun", score: 91, rating: 4.7 },
  { month: "Jul", score: 93, rating: 4.7 },
  { month: "Aug", score: 92, rating: 4.7 },
  { month: "Sep", score: 94, rating: 4.8 },
  { month: "Oct", score: 93, rating: 4.7 },
  { month: "Nov", score: 94, rating: 4.8 },
  { month: "Dec", score: 94, rating: 4.7 },
];

export const mockForecast = [
  { period: "Next 30 days", expectedReviews: 145, predictedRating: 4.8, potentialNegative: 8, confidence: 87 },
  { period: "Next 60 days", expectedReviews: 298, predictedRating: 4.8, potentialNegative: 15, confidence: 79 },
  { period: "Next 90 days", expectedReviews: 461, predictedRating: 4.9, potentialNegative: 21, confidence: 72 },
];

export const mockCompetitors = [
  {
    id: "comp_1",
    name: "Austin Family Care",
    address: "300 E Cesar Chavez, Austin TX",
    googleRating: 4.5,
    googleReviews: 892,
    healthgradesRating: 4.3,
    monthlyReviews: 28,
    topPraise: ["friendly staff", "quick appointments"],
    topComplaints: ["billing issues", "wait times"],
    trend: "improving",
  },
  {
    id: "comp_2",
    name: "Capital City Medical",
    address: "500 W MLK Blvd, Austin TX",
    googleRating: 4.2,
    googleReviews: 634,
    healthgradesRating: 4.0,
    monthlyReviews: 19,
    topPraise: ["clean facility", "professional doctors"],
    topComplaints: ["long waits", "hard to schedule"],
    trend: "stable",
  },
  {
    id: "comp_3",
    name: "South Austin Wellness",
    address: "2900 S Lamar Blvd, Austin TX",
    googleRating: 4.6,
    googleReviews: 1124,
    healthgradesRating: 4.5,
    monthlyReviews: 45,
    topPraise: ["great doctors", "attentive care"],
    topComplaints: ["expensive", "parking"],
    trend: "growing",
  },
];

export const mockProviders = [
  { id: "prov_1", name: "Dr. Emily Chen", specialty: "Internal Medicine", location: "Main Street Medical Center", avgRating: 4.9, totalReviews: 412, satisfactionScore: 97, responseTime: "1.0h" },
  { id: "prov_2", name: "Dr. James Whitfield", specialty: "Dentistry", location: "Downtown Dental & Wellness", avgRating: 4.8, totalReviews: 298, satisfactionScore: 95, responseTime: "0.8h" },
  { id: "prov_3", name: "Dr. Priya Sharma", specialty: "Family Medicine", location: "Main Street Medical Center", avgRating: 4.7, totalReviews: 341, satisfactionScore: 93, responseTime: "1.4h" },
  { id: "prov_4", name: "Dr. Marcus Johnson", specialty: "Pediatrics", location: "Westside Family Clinic", avgRating: 4.6, totalReviews: 287, satisfactionScore: 91, responseTime: "2.1h" },
  { id: "prov_5", name: "Dr. Sofia Reyes", specialty: "OB/GYN", location: "Main Street Medical Center", avgRating: 4.8, totalReviews: 256, satisfactionScore: 96, responseTime: "1.2h" },
];

export const mockSentimentTrend = [
  { date: "Week 1", positive: 78, neutral: 14, negative: 8 },
  { date: "Week 2", positive: 82, neutral: 11, negative: 7 },
  { date: "Week 3", positive: 79, neutral: 13, negative: 8 },
  { date: "Week 4", positive: 85, neutral: 10, negative: 5 },
  { date: "Week 5", positive: 88, neutral: 9, negative: 3 },
  { date: "Week 6", positive: 86, neutral: 10, negative: 4 },
  { date: "Week 7", positive: 90, neutral: 7, negative: 3 },
  { date: "Week 8", positive: 87, neutral: 9, negative: 4 },
];

export const mockVoiceThemes = [
  { theme: "Friendly Staff", mentions: 412, sentiment: "positive", trend: "+12%" },
  { theme: "Wait Times", mentions: 187, sentiment: "negative", trend: "+8%" },
  { theme: "Doctor Quality", mentions: 398, sentiment: "positive", trend: "+5%" },
  { theme: "Clean Facility", mentions: 256, sentiment: "positive", trend: "+3%" },
  { theme: "Billing Issues", mentions: 134, sentiment: "negative", trend: "+15%" },
  { theme: "Easy Scheduling", mentions: 89, sentiment: "positive", trend: "+22%" },
  { theme: "Communication", mentions: 201, sentiment: "positive", trend: "+7%" },
  { theme: "Appointment Availability", mentions: 78, sentiment: "negative", trend: "-4%" },
];

export const mockAnalyticsData = {
  seoKeywords: [
    { keyword: "urgent care austin", rank: 3, volume: 2400, trend: "+2" },
    { keyword: "family doctor austin", rank: 7, volume: 1900, trend: "+4" },
    { keyword: "dentist downtown austin", rank: 2, volume: 1200, trend: "+1" },
    { keyword: "best pediatrician austin", rank: 5, volume: 890, trend: "+3" },
    { keyword: "primary care westlake", rank: 4, volume: 640, trend: "0" },
  ],
  referralFunnel: [
    { stage: "Happy Patients", count: 1240 },
    { stage: "Referral Requests Sent", count: 847 },
    { stage: "Referral Links Clicked", count: 412 },
    { stage: "New Patient Inquiries", count: 189 },
    { stage: "Appointments Booked", count: 134 },
  ],
};

export const mockAuditLogs = [
  { id: 1, user: "admin@healthfirst.com", action: "Campaign Created", resource: "Post-Visit Feedback Request", timestamp: "2026-07-06 14:32:10", ip: "192.168.1.42" },
  { id: 2, user: "manager@healthfirst.com", action: "Review Response Approved", resource: "Google Review #rev_3", timestamp: "2026-07-06 13:18:44", ip: "192.168.1.55" },
  { id: 3, user: "admin@healthfirst.com", action: "User Invited", resource: "dr.sharma@healthfirst.com", timestamp: "2026-07-06 11:02:19", ip: "192.168.1.42" },
  { id: 4, user: "staff@westside.com", action: "Patient Feedback Viewed", resource: "Patient #pat_3", timestamp: "2026-07-06 10:44:33", ip: "10.0.0.12" },
];

export const mockTeamMembers = [
  { id: "user_1", name: "Alexandra Hart", email: "a.hart@healthfirst.com", role: "ORG_ADMIN", location: "All Locations", lastActive: "Just now", avatar: "AH" },
  { id: "user_2", name: "Marcus Chen", email: "m.chen@healthfirst.com", role: "CLINIC_MANAGER", location: "Main Street Medical Center", lastActive: "2h ago", avatar: "MC" },
  { id: "user_3", name: "Priya Sharma", email: "p.sharma@healthfirst.com", role: "STAFF", location: "Main Street Medical Center", lastActive: "5h ago", avatar: "PS" },
  { id: "user_4", name: "James O'Brien", email: "j.obrien@healthfirst.com", role: "CLINIC_MANAGER", location: "Westside Family Clinic", lastActive: "1d ago", avatar: "JO" },
  { id: "user_5", name: "Sofia Rivera", email: "s.rivera@healthfirst.com", role: "VIEWER", location: "Downtown Dental & Wellness", lastActive: "3h ago", avatar: "SR" },
];

export const mockDepartmentScorecards = [
  { department: "Reception & Check-in", rating: 4.2, change: "+0.3", reviews: 524, alert: false },
  { department: "Nursing Staff", rating: 4.8, change: "+0.1", reviews: 812, alert: false },
  { department: "Doctors & Providers", rating: 4.9, change: "Stable", reviews: 1140, alert: false },
  { department: "Billing & Insurance", rating: 3.8, change: "-0.4", reviews: 312, alert: true, reason: "Invoicing delays" },
  { department: "Laboratory & Diagnostics", rating: 4.5, change: "+0.2", reviews: 198, alert: false },
  { department: "Pharmacy / Discharges", rating: 4.4, change: "+0.1", reviews: 284, alert: false },
];

export const mockCopilotResponses = [
  {
    query: "Why are ratings declining at Westside?",
    answer: "Based on sentiment analysis of portal chats and private feedback forms over the last 14 days, Westside Family Clinic is experiencing a **0.4★ decline** in average patient satisfaction. The primary drivers are:\n1. **Average Wait Times** increased from 15 mins to **28 mins** due to peak hours staff shortages on Tuesday afternoons.\n2. **Billing confusion**: 14 billing complaints logged regarding co-pay clarity.\n\n*Recommended action*: Shift 1 nursing assistant to front-desk support on Tuesday afternoons and enable online pre-check-in."
  },
  {
    query: "Which clinic has the happiest patients?",
    answer: "Downtown Dental & Wellness currently holds the highest reputation score of **92** with an average patient rating of **4.7★** and an NPS of **76**. Staff friendliness is praised in **94% of mentions**, and wait times average under **10 minutes** due to online registration adoption."
  },
  {
    query: "What are the top patient complaints this month?",
    answer: "Across all locations, the top patient complaints logged are:\n1. **Wait Time (32% of complaints)**: Especially high at Westside Clinic.\n2. **Billing Clarity (15% of complaints)**: Patient inquiries on insurance processing.\n3. **Appointment Scheduling (8% of complaints)**: Difficulty booking same-week appointments."
  },
  {
    query: "Which provider improved most this month?",
    answer: "**Dr. Marcus Johnson** (Pediatrics, Westside Family Clinic) improved his average patient rating from **4.3★ to 4.6★** this month. Patient mentions highlight a 'much warmer demeanor' and 'efficient consults' following the optimization of patient triage flows."
  }
];

export const mockComplaints = [
  { id: "comp_1", patientName: "Linda Kowalski", provider: "Dr. Priya Sharma", department: "Reception & Check-in", description: "Waited 42 minutes after scheduled check-in time with zero updates from front-desk staff.", status: "investigating", slaRemaining: "1h 12m", priority: "high", createdAt: "2026-07-06 11:30:00" },
  { id: "comp_2", patientName: "Rachel Green", provider: "Dr. Priya Sharma", department: "Billing & Insurance", description: "Double-charged co-pay on secondary insurance validation.", status: "resolved", slaRemaining: "Closed", priority: "medium", createdAt: "2026-07-05 09:15:00" },
  { id: "comp_3", patientName: "James Rodriguez", provider: "Dr. Marcus Johnson", department: "Reception & Check-in", description: "Arrived at 2 PM but doctor was running 20 minutes behind without notice.", status: "assigned", slaRemaining: "0h 42m", priority: "high", createdAt: "2026-07-06 14:00:00" },
  { id: "comp_4", patientName: "David Walker", provider: "Dr. Marcus Johnson", department: "Pharmacy / Discharges", description: "Discharge prescriptions not forwarded to pharmacy upon check-out.", status: "complaint", slaRemaining: "1h 55m", priority: "medium", createdAt: "2026-07-06 13:45:00" }
];


